name: discord-stats

on:
  workflow_dispatch:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch GitHub stars and forks
        id: repo-stats
        run: |
          # Hent repo info med GitHub API
          stats=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY})
          stars=$(echo "$stats" | jq '.stargazers_count')
          forks=$(echo "$stats" | jq '.forks_count')
          echo "stars=$stars" >> $GITHUB_OUTPUT
          echo "forks=$forks" >> $GITHUB_OUTPUT

      - name: Fetch latest release download count
        id: downloads
        run: |
          # Hent seneste release info
          release=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest)
          downloads=$(echo "$release" | jq '[.assets[]?.download_count] | add // 0')
          echo "downloads=$downloads" >> $GITHUB_OUTPUT

      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          stars="${{ steps.repo-stats.outputs.stars }}"
          forks="${{ steps.repo-stats.outputs.forks }}"
          downloads="${{ steps.downloads.outputs.downloads }}"
          message="**Windows Maintenance Tool – GitHub stats**\n⭐ Stars: $stars\n🍴 Forks: $forks\n📥 Downloads (latest): $downloads"
          json_message=$(printf '%s' "$message" | python3 -c "import json,sys; print(json.dumps(sys.stdin.read()))")
          payload="{\"content\": $json_message}"
          curl -H "Content-Type: application/json" -X POST -d "$payload" $DISCORD_WEBHOOK
