- name: Send message to Discord
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    STARS: ${{ env.STARS }}
    FORKS: ${{ env.FORKS }}
    DOWNLOADS: ${{ env.DOWNLOADS }}
  run: |
    message="**Windows Maintenance Tool – GitHub stats**\n⭐ Stars: $STARS\n🍴 Forks: $FORKS\n📥 Downloads (latest): $DOWNLOADS"
    echo "Sending message: $message"
    payload="{\"content\": \"$message\"}"
    response=$(curl -s -w "%{http_code}" -o response.txt -H "Content-Type: application/json" -X POST -d "$payload" $DISCORD_WEBHOOK)
    cat response.txt
    echo "Discord Response code: $response"
