name: Discord Stats

on:
  workflow_dispatch:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          STARS: ${{ env.STARS }}
          FORKS: ${{ env.FORKS }}
          DOWNLOADS: ${{ env.DOWNLOADS }}
        run: |
          message="**Windows Maintenance Tool – GitHub stats**\n⭐ Stars: ${STARS}\n🍴 Forks: ${FORKS}\n📥 Downloads (latest): ${DOWNLOADS}"
          json_message=$(python3 -c "import json,os; print(json.dumps(os.environ['message']))" message="$message")
          payload="{\"content\": $json_message}"
          curl -H "Content-Type: application/json" -X POST -d "$payload" $DISCORD_WEBHOOK
