name: discord-stats

on:
  workflow_dispatch:
  push:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          message=":tada: Workflow virker 100%! :rocket:\n\nDenne besked er sendt fra GitHub Actions til Discord-webhook."
          # Escape beskeden til JSON
          json_message=$(printf '%s' "$message" | python3 -c "import json,sys; print(json.dumps(sys.stdin.read()))")
          payload="{\"content\": $json_message}"
          curl -H "Content-Type: application/json" -X POST -d "$payload" $DISCORD_WEBHOOK
